model:
  base_learning_rate: 1.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    identity: True
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: singingvoice
    cond_stage_key: features
    image_size: [800,40]  #change from a number into a list
    channels: 1 #only 1 for audio
    concat_mode: False #using cross attention
    monitor: val/loss
    scheduler_config:
      target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        verbosity_interval: 0
        warm_up_steps: 1000
        max_decay_steps: 50000
        lr_start: 0.001
        lr_max: 0.1
        lr_min: 0.00001
    unet_config:  #改成transformer的
      target: ldm.modules.diffusionmodules.openaimodel.TransformerModel
      params:
        in_channels: 40  #the dimension of the latent space (from 40 to 10)
        out_channels: 40
        num_blocks: 3
        emb_channels: 256 #the dimension of the embedding space
        dropout: 0.1
        dims: 1
        num_heads: 8
        use_new_attention_order: True
    first_stage_config:
      target: ldm.models.autoencoder.IdentityFirstStage
    cond_stage_config: __is_first_stage__
