model:
  base_learning_rate: 1.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: singingvoice
    cond_stage_key: features
    image_size: [200,10]  #change from a number into a list
    channels: 1 #only 1 for audio
    concat_mode: False #using cross attention
    monitor: val/loss
    scheduler_config:
      target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        verbosity_interval: 0
        warm_up_steps: 1000
        max_decay_steps: 50000
        lr_start: 0.001
        lr_max: 0.1
        lr_min: 0.00001
    unet_config:  #改成transformer的
      # target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      # params:
      #   image_size: 64
      #   in_channels: 6 
      #   out_channels: 3
      #   model_channels: 128
      #   attention_resolutions:
      #   - 8
      #   - 4
      #   - 2
      #   num_res_blocks: 2
      #   channel_mult:
      #   - 1
      #   - 2
      #   - 3
      #   - 4
      #   num_heads: 8
      #   resblock_updown: true
      target: ldm.modules.diffusionmodules.openaimodel.TransformerModel
      params:
        in_channels: 6 
        out_channels: 3
        num_blocks: 3
        emb_channels: 128
        dropout: 0.0
        dims: 3
        num_heads: 8
        use_new_attention_order: True
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        monitor: val/rec_loss
        ckpt_path: "pretrain/first_stage/vq-f4/model.ckpt" #the path of the first stage model
        ddconfig:
          attn_type: none
          double_z: false
          z_channels: 3
          resolution: 800 #no used
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_first_stage__


data:
  target: main.DataModuleFromConfig
  params:
      batch_size: 8
      wrap: False
      num_workers: 1
      train:
          target: ldm.data.singvoice.SingVoice
          params:
              datapath: D:\math\NLP\project\Singing-Voice-Conversion-BingliangLi\preprocess
              data_type: train
              dataset: Opencpop
      validation:
          target: ldm.data.singvoice.SingVoice
          params:
              datapath: D:\math\NLP\project\Singing-Voice-Conversion-BingliangLi\preprocess
              data_type: test
              dataset: Opencpop

lightning:
  trainer:
    max_epochs: 200
    num_nodes: 1
    accelerator: 'gpu'
    gpus: "0"
